# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('comment_about_me', models.TextField()),
            ],
        ),
    ]
